export const defaultQuizData = [
  {
    name: "Quiz 1",
    ans: [
      "Reset Button",
      "AREF",
      "Ground Pin",
      "Digital Input/Output",
      "PWM",
      "USB Connection",
      "TX/RX ",
      "ATmega Microcontroller",
      "Power LED Indicator",
      "Voltage Regulator",
      "DC Power Barrel Jack",
      "3.3V Pin",
      "5V Pin",
      "Ground Pins",
      "Analog Pins",
    ],
    userAns: [],
    dateFinished: "",
    img: [require("./assets/quiz/1.png")],
  },
  {
    name: "Quiz 2",
    ans: [
      "Menu Bar",
      "Verify Button",
      "Upload Button",
      "New Sketch",
      "Sketch Name",
      "Open Existing Sketch",
      "Save Sketch",
      "Serial Monitor",
      "Code Area",
      "Message Area",
      "Text Console",
      "Board and Serial Port",
    ],
    userAns: [],
    dateFinished: "",
    img: [require("./assets/quiz/2-1.png")],
  },
  {
    name: "Quiz 2.1",
    ans: ["e", "b", "j", "d", "k", "a", "g", "h", "f", "c", "i", "l"],
    userAns: [],
    dateFinished: "",
    img: [require("./assets/quiz/2-2.png")],
  },
  {
    name: "Quiz 3",
    ans: [
      "Photoresistor",
      "Temperature Sensor",
      "DC Motor",
      "Piezo Element",
      "Potentiometer",
      "LED",
      "Pushbutton",
      "LCD",
      "Integrated Circuit",
      "Relay",
    ],
    userAns: [],
    dateFinished: "",
    img: [require("./assets/quiz/3.png"), require("./assets/quiz/3-1.png")],
  },
  {
    name: "Quiz 4",
    ans: ["Mode", "OUTPUT", "loop", "delay", "LOW"],
    userAns: [],
    dateFinished: "",
    img: [require("./assets/quiz/4.png")],
  },
  {
    name: "Quiz 5",
    ans: ["led", "loop", "if", "Write", "}"],
    userAns: [],
    dateFinished: "",
    img: [require("./assets/quiz/5.png")],
  },
  {
    name: "Quiz 6",
    ans: [1, 2, 1, 1, 2, 2, 1, 2, 1, 2],
    userAns: [],
    dateFinished: "",
    img: [require("./assets/quiz/6.png")],
  },
  {
    name: "Unit Test 1",
    ans: [
      "c",
      "b",
      "a",
      "d",
      "d",
      "a",
      "b",
      "c",
      "a",
      "c",
      "c",
      "d",
      "a",
      "d",
      "b",
      "a",
      "c",
      "d",
      "b",
      "a",
      "c",
      "c",
      "d",
      "b",
      "d",
      "c",
      "a",
      "a",
      "b",
      "d",
    ],
    userAns: [],
    dateFinished: "",
    img: [
      require("./assets/quiz/unit1.png"),
      require("./assets/quiz/unit1-1.png"),
      require("./assets/quiz/unit1-2.png"),
      require("./assets/quiz/unit1-3.png"),
    ],
  },
  {
    name: "Quiz 7",
    ans: ["c", "d", "a", "d", "a", "b", "c", "b"],
    userAns: [],
    dateFinished: "",
    img: [require("./assets/quiz/7.png")],
  },
  {
    name: "Quiz 8",
    ans: [
      ";",
      "void",
      "Mode",
      "OUTPUT",
      "{",
      "(",
      "digital",
      "LOW",
      "for",
      "delay",
    ],
    userAns: [],
    dateFinished: "",
    img: [require("./assets/quiz/8.png")],
  },
  {
    name: "Quiz 9",
    ans: ["b", "e", "j", "h", "i", "c", "g", "d", "a", "f"],
    userAns: [],
    dateFinished: "",
    img: [require("./assets/quiz/9.png")],
  },
  {
    name: "Quiz 10",
    ans: ["function type", "no", "terminate", "Function", "Parameters"],
    userAns: [],
    dateFinished: "",
    img: [require("./assets/quiz/10.png")],
  },
  {
    name: "Quiz 11",
    ans: [1, "written", "less than", 1, 1, 1, 1, 2, 1, 1],
    userAns: [],
    dateFinished: "",
    img: [require("./assets/quiz/11.png")],
  },
  {
    name: "Unit Test 2",
    ans: [
      "b",
      "d",
      "a",
      "c",
      "c",
      "d",
      "b",
      "a",
      "b",
      "c",
      "a",
      "c",
      "d",
      "b",
      "d",
      "a",
      "b",
      "c",
      "d",
      "b",
      "d",
      "b",
      "a",
      "b",
      "c",
      "c",
      "d",
      "a",
      "a",
      "b",
    ],
    userAns: [],
    dateFinished: "",
    img: [
      require("./assets/quiz/unit2.png"),
      require("./assets/quiz/unit2-1.png"),
    ],
  },
];
