export const defaultQuizData = [
  {
    id: 1,
    name: "Quiz 1",
    ans: [
      "Reset Button",
      "AREF",
      "Ground Pin",
      "Digital Input/Output",
      "PWM",
      "USB Connection",
      "TX/RX ",
      "ATmega Microcontroller",
      "Power LED Indicator",
      "Voltage Regulator",
      "DC Power Barrel Jack",
      "3.3V Pin",
      "5V Pin",
      "Ground Pins",
      "Analog Pins",
    ],
    userAns: [],
    dateFinished: "",
    type: 1,
    examType: 1,
    img: [require("./assets/quiz/1-1.png"), require("./assets/quiz/1-2.png")],
  },
  // {
  //   id: 2,
  //   name: "Quiz 3",
  //   ans: [
  //     "Menu Bar",
  //     "Verify Button",
  //     "Upload Button",
  //     "New Sketch",
  //     "Sketch Name",
  //     "Open Existing Sketch",
  //     "Save Sketch",
  //     "Serial Monitor",
  //     "Code Area",
  //     "Message Area",
  //     "Text Console",
  //     "Board and Serial Port",
  //   ],
  //   userAns: [],
  //   dateFinished: "",
  //   type: 1,
  //   examType: 1,
  //   img: [require("./assets/quiz/2-1.png"),require("./assets/quiz/2-2.png"),require("./assets/quiz/2-3.png"),require("./assets/quiz/2-4.png")],
  // },
  {
    id: 3,
    name: "Quiz 2",
    ans: ["e", "b", "j", "d", "k", "a", "g", "h", "f", "c", "i", "l"],
    userAns: [],
    dateFinished: "",
    type: 1,
    examType: 1,
    img: [
      require("./assets/quiz/2-1.png"),
      require("./assets/quiz/2-2.png"),
      require("./assets/quiz/2-3.png"),
      require("./assets/quiz/2-4.png"),
    ],
  },
  {
    id: 4,
    name: "Quiz 3",
    ans: [
      "Photoresistor",
      "Temperature Sensor",
      "DC Motor",
      "Piezo Element",
      "Potentiometer",
      "LED",
      "Pushbutton",
      "LCD",
      "Integrated Circuit",
      "Relay",
    ],
    userAns: [],
    dateFinished: "",
    type: 1,
    examType: 1,
    img: [
      require("./assets/quiz/3-1.png"),
      require("./assets/quiz/3-2.png"),
      require("./assets/quiz/3-3.png"),
      require("./assets/quiz/3-4.png"),
    ],
  },
  {
    id: 5,
    name: "Quiz 4",
    ans: ["Mode", "OUTPUT", "loop", "delay", "LOW"],
    userAns: [],
    dateFinished: "",
    type: 1,
    examType: 1,
    img: [require("./assets/quiz/4-1.png")],
  },
  {
    id: 6,
    name: "Quiz 5",
    ans: ["led", "loop", "if", "Write", "}"],
    userAns: [],
    dateFinished: "",
    type: 1,
    examType: 1,
    img: [require("./assets/quiz/5-1.png")],
  },
  {
    id: 7,
    name: "Quiz 6",
    ans: [1, 2, 1, 1, 2, 2, 1, 2, 1, 2],
    userAns: [],
    dateFinished: "",
    type: 2,
    examType: 1,
    img: [require("./assets/quiz/6-1.png")],
  },
  {
    id: 8,
    name: "Unit Test 1",
    ans: [
      "c",
      "b",
      "a",
      "d",
      "d",
      "a",
      "b",
      "c",
      "a",
      "c",
      "c",
      "d",
      "a",
      "d",
      "b",
      "a",
      "c",
      "d",
      "b",
      "a",
      "c",
      "c",
      "d",
      "b",
      "d",
      "c",
      "a",
      "a",
      "b",
      "d",
    ],
    userAns: [],
    dateFinished: "",
    type: 0,
    examType: 2,
    img: [
      require("./assets/quiz/u1-1.png"),
      require("./assets/quiz/u1-2.png"),
      require("./assets/quiz/u1-3.png"),
      require("./assets/quiz/u1-4.png"),
      require("./assets/quiz/u1-5.png"),
      require("./assets/quiz/u1-6.png"),
    ],
  },
  {
    id: 9,
    name: "Quiz 7",
    ans: ["c", "d", "a", "d", "a", "b", "c", "b"],
    userAns: [],
    dateFinished: "",
    type: 0,
    examType: 1,
    img: [require("./assets/quiz/7-1.png")],
  },
  {
    id: 10,
    name: "Quiz 8",
    ans: [
      ";",
      "void",
      "Mode",
      "OUTPUT",
      "{",
      "(",
      "digital",
      "LOW",
      "for",
      "delay",
    ],
    userAns: [],
    dateFinished: "",
    type: 1,
    examType: 1,
    img: [require("./assets/quiz/8-1.png"), require("./assets/quiz/8-2.png")],
  },
  {
    id: 11,
    name: "Quiz 9",
    ans: ["b", "e", "j", "h", "i", "c", "g", "d", "a", "f"],
    userAns: [],
    dateFinished: "",
    type: 1,
    examType: 1,
    img: [require("./assets/quiz/9-1.png")],
  },
  {
    id: 12,
    name: "Quiz 10",
    ans: ["function type", "no", "terminate", "Function", "Parameters"],
    userAns: [],
    dateFinished: "",
    type: 1,
    examType: 1,
    img: [require("./assets/quiz/10-1.png"), require("./assets/quiz/10-2.png")],
  },
  {
    id: 13,
    name: "Quiz 11",
    ans: [
      "true",
      "written",
      "less than",
      "true",
      "true",
      "true",
      "true",
      "2",
      "true",
      "true",
    ],
    userAns: [],
    dateFinished: "",
    type: 1,
    examType: 1,
    img: [require("./assets/quiz/11-1.png")],
  },
  {
    id: 14,
    name: "Unit Test 2",
    ans: [
      "b",
      "d",
      "a",
      "c",
      "c",
      "d",
      "b",
      "a",
      "b",
      "c",
      "a",
      "c",
      "d",
      "b",
      "d",
      "a",
      "b",
      "c",
      "d",
      "b",
      "d",
      "b",
      "a",
      "b",
      "c",
      "c",
      "d",
      "a",
      "a",
      "b",
    ],
    userAns: [],
    type: 0,
    examType: 2,
    dateFinished: "",
    img: [
      require("./assets/quiz/u2-1.png"),
      require("./assets/quiz/u2-2.png"),
      require("./assets/quiz/u2-3.png"),
      require("./assets/quiz/u2-4.png"),
    ],
  },
];
