export const defaultQuizData = [
  {
    name: "Quiz 1",
    ans: [
      "Reset Button",
      "AREF",
      "Ground Pin",
      "Digital Input/Output",
      "PWM",
      "USB Connection",
      "TX/RX ",
      "ATmega Microcontroller",
      "Power LED Indicator",
      "Voltage Regulator",
      "DC Power Barrel Jack",
      "3.3V Pin",
      "5V Pin",
      "Ground Pins",
      "Analog Pins",
    ],
    userAns: [],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
  {
    name: "Quiz 2",
    ans: [
      "Menu Bar",
      "Verify Button",
      "Upload Button",
      "New Sketch",
      "Sketch Name",
      "Open Existing Sketch",
      "Save Sketch",
      "Serial Monitor",
      "Code Area",
      "Message Area",
      "Text Console",
      "Board and Serial Port",
    ],
    userAns: [],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
  {
    name: "Quiz 2.1",
    ans: ["e", "b", "j", "d", "k", "a", "g", "h", "f", "c", "i", "l"],
    userAns: [],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
  {
    name: "Quiz 3",
    ans: ["Mode", "OUTPUT", "loop", "delay", "LOW"],
    userAns: [],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
  {
    name: "Quiz 4",
    ans: ["led", "loop", "if", "Write", "}"],
    userAns: [],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
  {
    name: "Quiz 5",
    ans: [],
    userAns: [1, 2, 1, 1, 2, 2, 1, 2, 1, 2],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
  {
    name: "Quiz 6",
    ans: [],
    userAns: [
      "c",
      "b",
      "a",
      "d",
      "d",
      "a",
      "b",
      "c",
      "a",
      "c",
      "c",
      "d",
      "a",
      "d",
      "b",
      "a",
      "c",
      "d",
      "b",
      "a",
      "c",
      "c",
      "d",
      "b",
      "d",
      "c",
      "a",
      "a",
      "b",
      "d",
    ],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
  {
    name: "Quiz 7",
    ans: ["c", "d", "a", "d", "a", "b", "c", "b"],
    userAns: [],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
  {
    name: "Quiz 8",
    ans: [
      ";",
      "void",
      "Mode",
      "OUTPUT",
      "{",
      "(",
      "digital",
      "LOW",
      "for",
      "delay",
    ],
    userAns: [],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
  {
    name: "Quiz 9",
    ans: ["b", "e", "j", "h", "i", "c", "g", "d", "a", "f"],
    userAns: [],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
  {
    name: "Quiz 10",
    ans: ["function type", "no", "terminate", "Function", "Parameters"],
    userAns: [],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
  {
    name: "Quiz 11",
    ans: [1, "written", "less than", 1, 1, 1, 1, 2, 1, 1],
    userAns: [],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
  {
    name: "Quiz 12",
    ans: [
      "b",
      "d",
      "a",
      "c",
      "c",
      "d",
      "b",
      "a",
      "b",
      "c",
      "a",
      "c",
      "d",
      "b",
      "d",
      "a",
      "b",
      "c",
      "d",
      "b",
      "d",
      "b",
      "a",
      "b",
      "c",
      "c",
      "d",
      "a",
      "a",
      "b",
    ],
    userAns: [],
    dateFinished: "",
    img: require("./assets/quiz/1.png"),
  },
];
